spring:
  cloud:
    gateway:
      routes:
        - id: orders
            uri: lb://PRODUCTS-SERVICE
            predicates:
              - Path=/api/products
            filters:
              - RewritePath=/api/(?<products>.*), /$\{products}
        - id: payments
          uri: lb://PAYMENTS-SERVICE
          predicates:
            - Path=/api/payments
          filters:
            - RewritePath=/api/(?<payments>.*), /$\{payments}
        - id: orders
          uri: lb://ORDERS-SERVICE
          predicates:
            - Path=/api/orders
          filters:
            - RewritePath=/api/(?<orders>.*), /$\{orders}