server:
  port: 9002
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: payments-topic
          content-type: application/json
          groups: orders
broker-fee: "{cipher}429e207dff27445529699776fea6a88bff0910d779ccfdc29b85966c2d885151"