POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "amount": 1000,
  "creditCard": {
    "number": "1234567789",
    "cvv": 645,
    "expirationDate": "2029-12-10T12:00:00"
  }
}

###

POST http://localhost:8080/api/orders
Accept: application/json
Content-Type: application/json

{
  "products": [
    {
      "id": 1,
      "name": "Microservices in practice (e-book)"
    }
  ]
}

###

POST http://localhost:8080/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "Microservices in practice (e-book)",
  "description": "Book",
  "price": 200
}

###

GET http://localhost:8080/api/products?nameFragment=Micro
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8888/monitor
Content-Type: application/x-www-form-urlencoded

path=orders-service

###

POST http://localhost:8888/encrypt

spring

###

POST http://localhost:8888/decrypt

aae507a85c0fd094eff81e5a996a3733e80b8ffabddf2428e63692deb0ab65c8

###

POST http://localhost:8080/api/identity
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "username": "jan",
  "password:": "123"
}