POST http://localhost:8080/payments-service/payments
Accept: application/json
Content-Type: application/json

{
  "amount": 1000,
  "creditCard": {
    "number": "1234567789",
    "cvv": 645,
    "expirationDate": "2029-12-10T12:00:00"
  }
}

###